# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-12 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklist',
            options={'verbose_name': '\u672c\u5b50\u8d44\u6e90', 'verbose_name_plural': '\u672c\u5b50\u8d44\u6e90'},
        ),
    ]
