# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-14 13:03
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='name',
        ),
        migrations.AlterField(
            model_name='book',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u672c\u5b50\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='book_list',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u672c\u5b50\u56fe\u7247'),
        ),
    ]
