# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-14 13:09
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20170414_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='detail',
        ),
        migrations.AddField(
            model_name='book',
            name='book_list',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u672c\u5b50\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='\u672c\u5b50\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(max_length=300, upload_to='book/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
        migrations.DeleteModel(
            name='BookList',
        ),
    ]
