# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-24 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_music_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='tag',
            field=models.CharField(choices=[('zy', '\u6cbb\u6108'), ('rx', '\u71c3\u5411'), ('love', '\u604b\u7231'), ('sad', '\u60b2\u4f24'), ('cyy', '\u7eaf\u97f3\u4e50'), ('code', '\u4ee3\u7801\u4eba\u58eb')], default='grzh', max_length=50, verbose_name='\u97f3\u4e50\u7c7b\u578b'),
        ),
    ]
