# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-24 23:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20170424_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7ae0\u8282\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7ae0\u8282',
                'verbose_name_plural': '\u7ae0\u8282',
            },
        ),
        migrations.CreateModel(
            name='LessonMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u97f3\u4e50\u540d\u79f0')),
                ('music_url', models.FileField(max_length=200, upload_to='music/resource/%Y/%m', verbose_name='\u97f3\u4e50\u6587\u4ef6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Lesson', verbose_name='\u7ae0\u8282')),
            ],
            options={
                'verbose_name': '\u97f3\u4e50\u6587\u4ef6',
                'verbose_name_plural': '\u97f3\u4e50\u6587\u4ef6',
            },
        ),
        migrations.RemoveField(
            model_name='music',
            name='music_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music', verbose_name='\u97f3\u4e50\u540d'),
        ),
    ]
