# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-24 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20170424_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmusic',
            name='image',
            field=models.ImageField(default='', max_length=300, upload_to='music/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
        migrations.AlterField(
            model_name='lessonmusic',
            name='music_url',
            field=models.FileField(default='', max_length=200, upload_to='music/resource/%Y/%m', verbose_name='\u97f3\u4e50\u6587\u4ef6'),
        ),
    ]
