# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-25 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20170424_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmusic',
            name='singer',
            field=models.CharField(default='', max_length=100, verbose_name='\u6b4c\u624b\u540d\u5b57'),
        ),
    ]
