# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-25 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_lessonmusic_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmusic',
            name='lrc',
            field=models.TextField(default='', verbose_name='\u6b4c\u8bcd'),
        ),
    ]
