# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_lessonmusic_lrc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='lesson_name',
        ),
        migrations.RenameField(
            model_name='lessonmusic',
            old_name='name',
            new_name='lessonMusic_name',
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u4e13\u8f91\u540d'),
        ),
    ]
