# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20170426_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonmusic',
            old_name='image',
            new_name='music_image',
        ),
    ]
