# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-20 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdone', '0005_usercomments_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '\u89c6\u9891'), (2, '\u97f3\u4e50'), (3, '\u672c\u5b50'), (4, '\u6587\u7ae0'), (5, 'up\u4e3b')], default=1, verbose_name='\u6536\u85cf\u7c7b\u578b'),
        ),
    ]
