# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-16 11:09
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='video_name',
        ),
        migrations.AlterField(
            model_name='movies',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='\u89c6\u9891\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u89c6\u9891\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u89c6\u9891\u540d'),
        ),
    ]
