# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-16 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170416_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('dh', '\u52a8\u753b'), ('fj', '\u756a\u5267'), ('gc', '\u9b3c\u755c'), ('kj', '\u79d1\u6280'), ('dsj', '\u7535\u89c6\u5267'), ('lf', '\u91cc\u756a')], default='dh', max_length=50, verbose_name='\u89c6\u9891\u7c7b\u578b'),
        ),
    ]
