# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 17:11
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8d44\u6e90\u540d')),
                ('desc', models.CharField(max_length=300, verbose_name='\u8d44\u6e90\u63cf\u8ff0')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570')),
                ('image', models.ImageField(max_length=300, upload_to='book/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('tag', models.CharField(choices=[('rj', '\u8f6f\u4ef6'), ('sr', '\u751f\u8089'), ('\u6e38\u620f', 'game'), ('jc', '\u6559\u7a0b'), ('qt', '\u5176\u4ed6')], default='qt', max_length=50, verbose_name='\u672c\u5b50\u7c7b\u578b')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='\u8d44\u6e90\u8be6\u60c5')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u5e03\u8005')),
            ],
            options={
                'verbose_name': '\u8d44\u6e90',
                'verbose_name_plural': '\u8d44\u6e90',
            },
        ),
    ]
