# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_url',
            field=models.TextField(default='', validators='\u8d44\u6e90\u7684\u94fe\u63a5\uff08\u767e\u5ea6\u4e91\u76d8\uff09'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tag',
            field=models.CharField(choices=[('rj', '\u8f6f\u4ef6'), ('sr', '\u751f\u8089'), ('\u6e38\u620f', 'game'), ('jc', '\u6559\u7a0b'), ('qt', '\u5176\u4ed6')], default='qt', max_length=50, verbose_name='\u8d44\u6e90\u7c7b\u578b'),
        ),
    ]
