# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-12 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='move',
            new_name='movie',
        ),
    ]
