# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-15 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lesson',
        ),
        migrations.AddField(
            model_name='video',
            name='movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='\u89c6\u9891'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u7ae0\u8282\u540d'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
