# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-16 00:00
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20170415_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='movie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='\u89c6\u9891\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u89c6\u9891\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u89c6\u9891\u540d'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
