# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-16 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20170416_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='movie',
        ),
    ]
