# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-16 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_lesson_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
